# Generated by Django 2.0.7 on 2018-07-07 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('birth_place', models.CharField(blank=True, help_text='Country and city. e.g. Saudi Arabia Jeddah', max_length=100, null=True, verbose_name='Birth Place')),
                ('mobile', models.CharField(help_text='Mobile number should be of this format "9665xxxxxxxx". <br>Use English numerals only. <br>Please make sure to activate promotional messages from your mobile provider.', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^(9665|٩٦٦٥)\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Mobile')),
                ('first_name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name (Arabic)')),
                ('second_name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Name (Arabic)')),
                ('third_name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Name (Arabic)')),
                ('family_name_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Family Name (Arabic)')),
                ('gender', models.CharField(choices=[('', '---'), ('M', 'Male'), ('F', 'Female')], default='', max_length=128, verbose_name='Gender')),
                ('picture', models.FileField(blank=True, null=True, upload_to=user_profile.models.upload_location_picture, verbose_name='Personal Picture')),
                ('resume', models.FileField(blank=True, null=True, upload_to=user_profile.models.upload_location_resume, verbose_name='upload your resume')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('candidate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to=settings.AUTH_USER_MODEL, validators=[django.core.validators.RegexValidator('^(1)\\d{9}$', message='You have entered an invalid Government ID')], verbose_name='Government ID')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250, null=True, verbose_name='Job title')),
                ('employer', models.CharField(max_length=250, null=True, verbose_name='Employer')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('experience', models.FileField(blank=True, null=True, upload_to=user_profile.models.upload_location_experience_letter, verbose_name='Experience letter')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='user_profile.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Elementary school', 'Elementary school'), ('Intermediate school', 'Intermediate school'), ('High school', 'High school'), ('Diploma', 'Diploma')], max_length=250, null=True, verbose_name='Type')),
                ('education', models.CharField(max_length=250, null=True, verbose_name='Education')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='user_profile.Applicant')),
            ],
        ),
    ]
